// frontend/src/app/layout.jsx

// import localFont from "next/font/local"; // この行を削除
import "./styles/globals.css"; // パスを修正

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        {children}
      </body>
    </html>
  );
}
