"""Ensure schema is up-to-date

Revision ID: c822077cbad5
Revises: c492447c2be9
Create Date: 2024-12-12 18:51:49.124987

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c822077cbad5'
down_revision = 'c492447c2be9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

